name: configuration
description: an custom package for webvify apps
version: 1.0.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  args: 2.4.0
  colorize: 3.0.0
  equatable: 2.0.5
  http: 0.13.5
  yaml: 3.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter